bootstrap:
	flux bootstrap github \
	--owner=robert-ovens \
	--repository=flux-demo \
	--branch=main \
	--read-write-key \
	--private-key-file ./flux-key \
	--verbose \
	--personal \
	--path=./clusters/$(environment)
